apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-local-pv-v3
spec:
  storageClassName: suibianv3
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/test"