apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webook-mysql-test-claim-v3
spec:
  storageClassName: suibianv3
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

  