// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/lalalalade/basic-go/wire/repository"
	"github.com/lalalalade/basic-go/wire/repository/dao"
)

// Injectors from wire.go:

func InitRepository() *repository.UserRepository {
	db := InitDB()
	userDAO := dao.NewUserDao(db)
	userRepository := repository.NewUserRepository(userDAO)
	return userRepository
}
